name: Task3 Qt CI

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/task3.yml"
      - "Task3QT/**"
  pull_request:
    paths:
      - "Task3QT/**"

jobs:
  desktop-build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Task3QT
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.5.3'
          host: 'linux'
          target: 'desktop'
          modules: 'qtmultimedia qt5compat'
          
      - name: Install dependencies (Linux)
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-dev libxkbcommon-x11-0 libpulse-dev libpulse-mainloop-glib0
          
      - name: Configure CMake
        run: cmake -B build -S . -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=ON
        
      - name: Build
        run: cmake --build build --config Release
        
      - name: Run Tests
        run: xvfb-run ctest --test-dir build --output-on-failure

  android-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Task3QT
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Install Qt for Android
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.5.3'
          host: 'linux'
          target: 'android'
          arch: 'android_armv7'
          modules: 'qtmultimedia'
          
      - name: Configure CMake for Android
        run: |
          QT_ANDROID_DIR=$(find /home/runner/work -type d -path "*/6.5.3/android_armv7" | head -n 1)
          QT_HOST_DIR=$(find /home/runner/work -type d -path "*/6.5.3/gcc_64" | head -n 1)
          
          echo "Найдена папка Qt для Android: $QT_ANDROID_DIR"
          echo "Найдена папка Qt для Host: $QT_HOST_DIR"
          
          cmake -B build-android -S . \
            -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_ROOT/build/cmake/android.toolchain.cmake \
            -DANDROID_ABI=armeabi-v7a \
            -DCMAKE_PREFIX_PATH="$QT_ANDROID_DIR" \
            -DQT_HOST_PATH="$QT_HOST_DIR"
            
      - name: Build Android APK
        run: cmake --build build-android --target apk